CREATE TABLE [Salon].[Modele] (
    [Mod_Id]    SMALLINT      IDENTITY (1, 1) NOT NULL,
    [Mod_Kod]   VARCHAR (10)  NOT NULL,
    [Mod_Nazwa] VARCHAR (100) NOT NULL,
    [Mrk_Id]    SMALLINT      CONSTRAINT [DF_Mrk_Id] DEFAULT ((-1)) NOT NULL,
    PRIMARY KEY CLUSTERED ([Mod_Id] ASC),
    CONSTRAINT [FK_Mrk_Id_Modele] FOREIGN KEY ([Mrk_Id]) REFERENCES [Salon].[Marki] ([Mrk_Id]) ON DELETE SET DEFAULT ON UPDATE SET DEFAULT,
    UNIQUE NONCLUSTERED ([Mod_Kod] ASC)
);

